# Generated by Django 2.2 on 2019-05-06 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biliApriori', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='output_con',
            new_name='outputcon',
        ),
        migrations.RenameModel(
            old_name='output_sup',
            new_name='outputsup',
        ),
    ]
