# Generated by Django 2.2 on 2019-05-06 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biliApriori', '0002_auto_20190506_0922'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='outputcon',
            new_name='output_con',
        ),
        migrations.RenameModel(
            old_name='outputsup',
            new_name='output_sup',
        ),
    ]
