# Generated by Django 2.2.1 on 2019-05-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biliApriori', '0003_auto_20190506_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='default_con',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedent_s', models.CharField(max_length=32)),
                ('consequent_s', models.CharField(max_length=32)),
                ('confidence', models.CharField(max_length=32)),
                ('lift', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='default_sup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_s', models.CharField(max_length=32)),
                ('freq', models.CharField(max_length=32)),
            ],
        ),
    ]
